### ISSUE TITLE
还是会有桌面图标啊

### ISSUE THREAD

**Issue by Jomust** [huclengyue/AutoLight#1]
下载的无icon版的，安装后还是有桌面图标。华为手机,emui11,抽屉桌面.
![Screenshot_20201208_013231_com huawei android launcher](https://user-images.githubusercontent.com/67638483/101384333-40309200-38f5-11eb-96c5-547b0bf9687a.jpg)

**Comment by appdev** [comment]
如果你确定自己没有安装错，你大概是华为的Features吧。。因为 manifest 中的确没有设置图标
